Add Doctor Checks to Driver and Verifier (#494)
* Fix README links

* Add driver doctor

* Check for empty systems with doctor

* Fix references to Test Kitchen

* Add note about familiarity with Test Kitchen

* Add note about `kitchen doctor` command

* Ensure doctor checks driver and verifier

* Clarify doctor output

* Add kitchen doctor acceptance test

* Add doctor to changelog

---------

Co-authored-by: Aaron Lane <2400330-aaron-lane@users.noreply.gitlab.com>

diff --git a/.github/workflows/delivery.yml b/.github/workflows/delivery.yml
--- a/.github/workflows/delivery.yml
+++ b/.github/workflows/delivery.yml
@@ -119,6 +119,21 @@ jobs:
         run: |
           chmod 400 ./test/terraform/$VERSION_MATCHER/backend-ssh/id_ed25519
           rake test:kitchen:backend-ssh-ubuntu
+      - name: Run Kitchen doctor
+        run: |
+          status=0
+          output="$(kitchen doctor doctor)"
+          if [[ $output != *"${{ matrix.operating-system }}.driver.client"* ]]
+          then
+            echo "kitchen doctor did not detect driver.client error"
+            status=1
+          fi
+          if [[ $output != *"${{ matrix.operating-system }}.verifier.systems"* ]]
+          then
+            echo "kitchen doctor did not detect verifier.systems error"
+            status=1
+          fi
+          exit $status
 
   release:
     name: "Release"
